### ISSUE TITLE
Display function return value

### ISSUE THREAD

**Issue by Trass3r** [microsoft/MIEngine#1027]
https://github.com/microsoft/vscode-cpptools/issues/3214

PoC for gdb: https://github.com/Trass3r/MIEngine/commit/4fda0e9427bff88c0b0ae0cd11e8f2b5830c2b10

But this really only works when stepping out of a function (also no way to get the name of the callee).
The question is how to intercept other step requests and transform them based on the current line of code, e.g. step over function call => step in and out, step over a return statement => step out.
https://github.com/microsoft/MIEngine/blob/54b7d6b6dcc11d99297bcad8df765870f4e80da0/src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs#L1621-L1643

**Comment by WardenGnaw** [comment]
I will have to investigate this further, but this is dependent on what GDB commands can do. 

You could convert STEP_OVER to be ExecStep and then ExecFinish in order to get the return value from a step over. This will slow down stepping since this is now two commands. 

I'm not sure if there is a way for GDB to inform the adapter that it just stepped over a return statement.

**Comment by Trass3r** [comment]
Yes I'm trying this heuristic right now:
```cpp
                    case enum_STEPKIND.STEP_OVER:
                        string line = await ConsoleCmdAsync("list", false, true);
                        if (line.Contains("return "))
                        {
                            await MICommandFactory.ExecStep(threadId);
                            await MICommandFactory.ExecFinish(threadId);
                            break;
                        }
```
But I think alas there's no way to determine when stepping over a function call.
