### ISSUE TITLE
Update 'App.VS.config' to cleanup duplicate assemblies for VS

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/MIEngine#1062]
Fix [App.VS.config](https://github.com/microsoft/MIEngine/blob/main/src/OpenDebugAD7/App.VS.config) to reference the DropFiles from OpenDebugAD7.csproj from PrivateAssemblies (or add a AssemblyResolve hook for that) so we don't need to drop a bunch of extra copies of dlls that VS will already drop. 

Looks like MS.VS.Interop* dlls are in `<VS_ROOT>\Common7\IDE\PublicAssemblies`

https://github.com/microsoft/MIEngine/blob/main/src/OpenDebugAD7/OpenDebugAD7.csproj#L170-L185

**Comment by andrewcrawley** [comment]
Just FYI - when I was originally doing this work, I tried having App.VS.config reference the debugger interop assemblies via relative paths, as you describe.  This worked fine when the VSIX was deployed at the expected path under VS, but broke the "F5 MIDebugEngine.sln" case where the VSIX ends up installed in %LOCALAPPDATA%, since the relative paths no longer line up.

**Comment by WardenGnaw** [comment]
Removed App.VS.config since OpenDebugAD7 has been moved to .NET 5
