### ISSUE TITLE
[VS Code] ReadMemory request causes cast exception on macOS

### ISSUE THREAD

**Issue by gareth-davies-img** [microsoft/MIEngine#1081]
I'm issuing a ReadMemory request from a VSCode extension using:

`const readMemoryResp = await vscode.debug.activeDebugSession.customRequest('readMemory', { memoryReference: memoryReference, count: count, offset: offset });`

It works absolutely fine on Windows. However on macOS (Catalina 10.15.7) the following exception occurs:

"Specified cast is not valid."

I have traced it to the following line of code:

`int hr = ((IDebugMemoryBytesDAP)m_engine).CreateMemoryContext(address, out memoryContext);`

in AD7DebugSession.cs in the function GetMemoryContext().

**Comment by WardenGnaw** [comment]
@gareth-davies-img Thank you for finding this bug and creating this issue.

One question, are you using your own custom engine and loading it with a different configuration or are you using [cppdbg.ad7Engine.json](https://github.com/microsoft/MIEngine/blob/main/src/OpenDebugAD7/cppdbg.ad7Engine.json) which uses MIEngine's [AD7Engine](https://github.com/microsoft/MIEngine/blob/9470e98d946772ed1ace9ab68e9fbd4d88090b42/src/MIDebugEngine/AD7.Impl/AD7Engine.cs#L38)? 

If you are using another engine, we will fix this type cast to check to see if `IDebugMemoryBytesDAP` is implemented before calling `CreateMemoryContext`. But if the cast fails, then the `readMemory` request will result in an error.

My first thought with this issue it may be a mono framework issue since it is working on Windows, which would use .NET Framework. One good way to check is to see if this call also fails in Linux.

We are planning to move to .NET Core which may fix this casting issue, if not we will need to file an issue on the runtime.

**Comment by gareth-davies-img** [comment]
@WardenGnaw Many thanks for looking at this issue.

We are using VSCode 1.51.1 and cpptools 1.1.2 out the box, so are using the standard cppdbg.ad7Engine.json.

And I can confirm that the same cast exception happens on Linux.

**Comment by WardenGnaw** [comment]
Yep. This most likely is a bug with mono and how it handles embedded interfaces.

We have not had the chance to test `readMemory` requests on macOS/Linux. 

https://github.com/microsoft/MIEngine/pull/1082 should fix the cast exception, but the cast may still fail in mono.
https://github.com/microsoft/MIEngine/pull/1075 is part of the progress to move to .NET Core. It is moving to an SDK styled csproj which should make it easier to convert it from .NET Framework v4.6.2 to .NET Core 5.

**Comment by gareth-davies-img** [comment]
I have found a fix that gets the `ReadMemory` working on mono (tested on both Linux and macOS) 😃

The fix is to set `EmbedInteropTypes` to `False` for `Microsoft.VisualStudio.Debugger.Interop.DAP` in both `MIDebugEngine.csproj` and `OpenDebugAD7.csproj`.

Let me know if you want me to create a PR with these changes, if this is of use in the interim before .NET Core.

**Comment by WardenGnaw** [comment]
We completed the move to .NET 5 and moved away from using `EmbedInteropTypes`. 

Closing this issue for now, but feel free to reopen if you are still encountering this issue.
