### ISSUE TITLE
ShowDisplayStrings = DisplayStringsState.ForVisualizedItems

### ISSUE THREAD

**Issue by RYDB3RG** [Microsoft/MIEngine#128]
HI
is there a reason `Natvis.ShowDisplayStrings` is not `DisplayStringsState.On` ?
it seems to prevent DisplayStrings from showing up

**Comment by gregg-miskelly** [comment]
I _think_ the answer is that we found that GDB was too slow at evaluating the display strings, so for visualized items we instead added a child node to show the visualized value instead. @paulmaybee do I have this right?

**Comment by RYDB3RG** [comment]
Can I make a PR that makes this a LaunchOption (bool ShowDisplayString, default=false) ?
I think having DisplayStrings show up immediately in datatips or watchwindow is pretty helpful, even when gdb isn't super fast.

**Comment by gregg-miskelly** [comment]
That is fine with me. @paulmaybee, @chuckries can you think of any gotchas that would make that undesirable?

**Comment by paulmaybee** [comment]
Seems ok.

**Comment by chuckries** [comment]
This would be inaccessible in the current Android/iOS project system scenarios since we would not be able to adjust the LaunchOptions to include this. We would have to expose it through the project system UI or make it also enabled through an environment variable or registry setting.

**Comment by gregg-miskelly** [comment]
Right, but we don't have any UI now (except for the command window) where we could stick this option in a user-exposed way. So adding it to the launch options XML will at least allow RYDB3RG to use it in his scenario (I am assuming you aren't doing iOS/Android development?).

**Comment by RYDB3RG** [comment]
Yes, PC only (x64), no iOS/Android. I wasn't aware that IOS/Android launcher work differently, I agree that it would be strange to not have this option in those platforms. I don't mind using a patched version myself, so I don't persist on a PR

**Comment by gregg-miskelly** [comment]
So on Android and iOS the launch options XML is something dynamically generated by the Visual C++ project system. So in order for this setting to be tweaked in that case, the Visual C++ project system would need to expose some UI and add in to the launch options XML that they created. So the new feature that you are creating will not be exposed to folks using our Android/iOS C++ tooling. But that is okay, you have still added support for this so we could add it to those project systems if we want. I would just recommend adding it to the 'common attributes' inside the XSD so that we can trivial get this support in any scenario that wants it.

**Comment by RYDB3RG** [comment]
I made a pullrequest: https://github.com/Microsoft/MIEngine/pull/133
