### ISSUE TITLE
Visual Studio appends activity name when expanding $(ApplicationId) fro build.gradle.template

### ISSUE THREAD

**Issue by todi1856** [Microsoft/MIEngine#653]
Hi,

when creating Android project, build.gradle.template is created with lines 
        defaultConfig.with {
            $(ApplicationId)
            minSdkVersion.apiLevel = 16
            targetSdkVersion.apiLevel = 23
        }

Let's say my application name is com.Android3.
when VS creates build.gradle, it changes $(ApplicationId) to **applicationId = "com.Android3.Android3"**, notice activity name is appended to the package name, this effectively changes package name and overrides  the one specified in AndroidManifest.xml...

This behavior is inconsistent with projects created from Android Studio.

$(ApplicationId) should be resolved to applicationId = "com.Android3" instead of applicationId = "com.Android3.Android3"

**Comment by gregg-miskelly** [comment]
Thanks. This isn't really an MIEngine issue - this is a C++ Android project system issue. But I will see if I can find some folks from that team to comment on this.

**Comment by IanMatthewHuff** [comment]
Hey todi1856. This indeed looks to be a hitch with the Android project system (which I work on). We don't follow issues on MIEngine so I've filed a bug internally on this issue for me to look into. If you want better tracking on when we are looking into your issue you can file the info that you are provided here:
https://developercommunity.visualstudio.com/spaces/8/index.html
And that will create a feedback ticket that I'll link to the bug so that you can get updated when it's being looked at and resolved.
