### ISSUE TITLE
Run without debug

### ISSUE THREAD

**Issue by digittigerw** [Microsoft/MIEngine#737]
Hi,  is VS "Debug -> Start without debugging" supported by MIEngine ? With my current integration, that command leads to error like "the program is not a win32 application". So it seems like that's not routed to MIEngine. 
Thanks.

**Comment by gregg-miskelly** [comment]
@digittigerw can you tell me more about what you are trying to do?

In Visual Studio, debug engines don't participate in "Start without debugging".

**Comment by digittigerw** [comment]
@gregg-miskelly I just try to allow my user/developer to download and run a program on device without attaching debugger. Or at least disable the "Start without debugging" command in the menu so that it won't lead to error.

**Comment by gregg-miskelly** [comment]
@digittigerw are you the owner of a project system that launches the MIEngine? Can you tell me a bit about what you are asking the MIEngine to do? (ex: launch a process, attach to a process, etc).

**Comment by digittigerw** [comment]
Yes, I'm writing an extension that extends MIEngine for our own target platform.  I can start debugger (gdb) to debug a program now. But I also want to launch a program on my target device without debugging it, namely download the binary and launch it then leave it alone.

**Comment by gregg-miskelly** [comment]
So what you want to do is to check for the DBGLAUNCH_NoDebug flag that is passed to the project system to start debugging. If you have the ability to communicate with the device without using GDB, you could then do that inside of your project system instead of calling the debugger service (IVsDebugger.LaunchDebugTargets[2/3/4]).

If you can only launch programs through GDB, you could fail the launch immediately with some sort of 'unsupported' error message.

**Comment by digittigerw** [comment]
Yes, I found the answer.  I can do that in my subclass of DebugLaunchProviderBase.  Thanks !
