### ISSUE TITLE
MIMode "gdb" wrongly assumes the type of Inferior; debugger pause does not work

### ISSUE THREAD

**Issue by haneefdm** [microsoft/MIEngine#844]
Okay, here is the scenario. Sorry, long

I am using GDB on my Mac (via MIEngine/cpptools) to debug a program/image running on a board connected to my USB/serial port. Pretty much everything works except for one huge thing. I cannot pause a running target. I can pause it using any other tool (Eclipse, gdb command line, even another VSCode extension, etc.). This is the 99.9% use case for embedded/IoT applications where they can't actually afford to have an entire OS/gdb running on the board. When I try to pause, nothing happens. I pretty much have to kill the VSCode Debug session, find and kill the gdb-server and/or gdb itself.

I think I know why this is happening. In [MICore/src/Debugger.cs, around line 707](https://github.com/Microsoft/MIEngine/blob/5ab89ebe0c8f3a45b1a49c2304923c19a549f02f/src/MICore/Debugger.cs#L707), you check to see if it is local gdb and assumes program is local too.

Then there is https://sourceware.org/bugzilla/show_bug.cgi?id=20035.

Well, that is only applicable to gdb executing native prorgrams. In our case, gdb is debugging a quasi-remote program in async mode. It is called "remote serial" or "extended remote serial". The local gdb talks to a gdb-server either using a serial port, local/remote IP address See [-target-select](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Target-Manipulation.html#GDB_002fMI-Target-Manipulation) doc.

Problem is that gdb-servers can create fake pids and thread-groups if they have to and gdb hasn't got a clue they are fake. Since MIEngine monitors and collects these pids, it tries to send a SIGINT to the debuggee which will never work. **Might even kill an innocent process on local machine? :-)**.

Using the gdb command ```info target``` When you debug something with gdb, you can figure out what kind of target it is even though gdb and executable are local...

With gdb running on my Mac and board connected to a USB port, it shows.

```
Symbols from "/Users/hdm/tmp/cystuff/demo/main_final.elf".
Extended remote serial target in gdb-specific protocol:
Debugging a target over a serial line.
	While running this, GDB does not access memory from...
Local exec file:
	`/Users/hdm/tmp/cystuff/demo/main_final.elf', file type elf32-littlearm.
	Entry point: 0x100802ce
	0x10080000 - 0x100811e4 is .text
        ...
```

With gdb running a local process on Windows/Cygwin, it will say 'Native process'

```
Symbols from "/cygdrive/j/VSCode/adv-cppdbg/test/stdc-threads/bin/main.exe".
Native process:
	Using the running image of child Thread 27012.0x5d9c.
	While running this, GDB does not access memory from...
Local exec file:
	`/cygdrive/j/VSCode/adv-cppdbg/test/stdc-threads/bin/main.exe', file type pei-x86-64.
	Entry point: 0x100401000
	0x0000000100401000 - 0x0000000100403040 is .text
```
Applies to ALL platforms but just for gdb. If you don't see 'Native process', you are debugging something not local. And '-exec interrupt' will work. I have proof. Signaling the Inferior obviously wont work. Unfortunately, I don't have a MI equivalent of ```info target```. I just did ```-exec info target``` You send an `-exec-interrupt`, gdb says, since I am running remote mode, I will pass it on to the gdb-server and they all report back to MIEngine/VSCode/User

You want to figure out the target type at the start of the session. There is another way, which is to look at the startup commands. Anyone who is doing this will have to execute '-target-select' command during startup, but there are 2-3 ways of doing it syntax wise. Logic for `IsLocalGdb()` and `IsRemoteGdb()` has to be reviewed and how they are used. May need isLocalGdbRemoteTarget() for instance. Lucky, these are `internal/private` all contained in that same file.

Let me know if you want my help fixing/testing this. I apologize, if I misread the code in MIEngine.

**Comment by haneefdm** [comment]
If my analysis is right (I hope I am wrong), it is a super serious problem. **MIEngine might kill a random process** Wanted to stress that.

**Comment by cynecx** [comment]
I think this is related to this issue: https://github.com/Microsoft/vscode-cpptools/issues/833.

**Comment by haneefdm** [comment]
@cynecx  Yes, it is. Thanks for the pointer. But there is more to it. When gdb is using a gdbserver (local or remote), pause/stop works everywhere now. I am testing my fix right now. Early next week, I hope to do a PR. If I can get cygwin/mingw to work reliably without a gdbserver, then we are golden. Lot of combinations to test :-)

The arm-none-eabi-gdb on Windows is actually a mingw compiled executable. `This GDB was configured as "--host=i686-w64-mingw32 --target=arm-none-eabi"`
`
There is another (separate) minor issue with 'stopAtEntry'. While it works, there is a better implementation. MIEngine should use a temporary breakpoint for this as breakpoints are very limited in embedded devices. My workaround is to not use this feature and do issue a temp. breakpoint in startup commands.

**Comment by gregg-miskelly** [comment]
Is there a reason you are using:

```
            "setupCommands": [
...
                {
                    "text": "target remote localhost:4242"
                },
```

Instead of: `"miDebuggerServerAddress": "localhost:4242",`

**Comment by haneefdm** [comment]
Hi @gregg-miskelly, not sure where you saw the 4242, but it is true that we use something like that
`-target-select remote localhost:3333`. We don't use the miDebuggerServerAddress because that requires us to launch the server separately (in another shell window). We typically launch both the server and gdb from the same button.... and they are kinda synchronized and far fewer manual steps.

A typical embedded setup looks something like
```
            "debugServerArgs": "-s ${workspaceRoot} -s /Applications/ModusToolbox_2.0/tools/openocd-2.2/scripts -s C:/Users/hdm/ModusToolbox_2.0/tools/openocd-2.2/scripts -f openocd.tcl",
            "serverStarted": "Info :.*Listening on port [0-9]+ for gdb connections",
            "setupCommands": [
                { "text": "-environment-cd ${workspaceRoot}" },
                { "text": "-gdb-set target-async on" },
                { "text": "-target-select extended-remote localhost:3333", "description": "connect to target", "ignoreFailures": false },
                { "text": "-file-exec-and-symbols main_final.elf", "description": "load file", "ignoreFailures": false},
                { "text": "-interpreter-exec console \"monitor reset init\""},
                { "text": "-target-download", "description": "flash target", "ignoreFailures": false },
                { "text": "-interpreter-exec console \"monitor reset run\""},
                { "text": "-interpreter-exec console \"monitor sleep 200\""},
                { "text": "-interpreter-exec console \"monitor psoc6 reset_halt sysresetreq\""},
                { "text": "-enable-pretty-printing" }
            ],
            "osx": {
                "MIMode": "gdb",
                "MIDebuggerPath": "arm-none-eabi-gdb",
                "debugServerPath": "/Applications/ModusToolbox_2.0/tools/openocd-2.2/bin/openocd"
            },
```
The first two lines in `setupCommands` are not needed because MIEngine already does this. And we need to select between 'remote' and 'extended-remote'. Doing it in setupCommands is more convenient and if we don't do it there, then we cannot erase/load the program into flash, do a proper reset/start and all that magic. gdbservers like OpenOCD/PyOCD, expect all that work to be done via gdb and don't provide any other way of doing it.

From what I understand, you either use the `miDebuggerServerAddress` or use the `debugServerPath`, not both. Btw, this same technique also works with cygwin and be able to pause using the normal debug buttons .. I know the workaround is to Control-C in the shell window. It only requires about 4 lines in the launch.json file, I don't recommend it but I am testing all the combinations.

When you use the '-target-select' command, I found out that gdb sends a pretty unique response and that is all we have to look for in MIEngine.

**Comment by haneefdm** [comment]
Btw, @gregg-miskelly, a remote target can also be a serial device like COM port or a /dev/ttyX which I don't think you can do using `miDebuggerServerAddress`

I am finished testing but I'd be thrilled if you can [review my changes here](https://github.com/haneefdm/MIEngine/commit/8fb5bd18d3d5f4ec2462f9d0122f12f5b1df993b#diff-c8a7af1631e47041679c15d5343c50d6)... I only had to touch one file, very few changes.

I did not have a Linux box, and I am in the process of installing one.

**Comment by gregg-miskelly** [comment]
Using `mode == "connected"` sounds reasonable. I think you would want to change `IsLocalGdb` to return `false` for these scenarios rather than making the change you have on line 620.

**Comment by gregg-miskelly** [comment]
I should add, your check is trying to determine exactly the same as `string.IsNullOrWhiteSpace(localLaunchOptions.MIDebuggerServerAddress)`. So you probably want to scrutinize any place where we are checking that. Unfortunately some of the places we check for that are during initialization when we probably haven't received the 'connected' massage. But here are two more places that you could fix:

```
                // MinGW sends a stopped event on attach. gdb<->gdbserver also sends a stopped event when first attached.
                // If this is a gdb<->gdbserver connection, ignore this as the entryPoint
                if (this._launchOptions is LocalLaunchOptions &&
                    !String.IsNullOrWhiteSpace(((LocalLaunchOptions)this._launchOptions).MIDebuggerServerAddress))
```
```
        private bool IsRemoteGdb()
        {
            return this.MICommandFactory.Mode == MIMode.Gdb &&
               (this._launchOptions is PipeLaunchOptions || this._launchOptions is UnixShellPortLaunchOptions ||
               (this._launchOptions is LocalLaunchOptions
                    && !String.IsNullOrEmpty(((LocalLaunchOptions)this._launchOptions).MIDebuggerServerAddress)));
        }
```

**Comment by haneefdm** [comment]
@gregg-miskelly, I had initially changed the implementations of `IsLocalGdb` and `IsRemoteGdb`, but I got uncomfortable with the original names (imply) of those methods and backed the changes out. May I propose the following:

- I will fold the `IsTargetRemoteOrExtendedRemote` uses into `IsLocalGdb` and `IsRemoteGdb`
- Rename `IsLocalGdb` and `IsRemoteGdb` to `IsLocalGdbTarget` and `IsRemoteGdbTarget`, with your permission
- Look for every place such checks are made to see what needs to be corrected - as you suggested
- I will leave the `IsTargetRemoteOrExtendedRemote` impl. alone as lldb also uses this and it will be good to know in the future if any debugger has used a remote target independent of gdb
- Remove the two `Debug.Asserts()` I added because I am less paranoid now.
- Test all the scenarios I can think of

Boy, cygwin is a beast to deal with. I tried so many things to make it behave to no avail. I tried `GenerateConsoleCtrlEvent`, sending SIGINT to gdb itself and none of it works. However, if connected to a gdbserver, it behaves properly with a -exec-interrupt. For development, I always stayed away from cygwin and mingw has its share of bugs (lots of buffer overflows).

**Comment by pieandcakes** [comment]
@haneefdm this is now in vscode-cpptools version `0.24.0-insiders`

**Comment by haneefdm** [comment]
Cool. Thanks.

**Comment by BillPlunkett** [comment]
I was elated when this issue was fixed in 2019 and have done a lot of successful cross-debugging with vscode since.  However, I am seeing this issue again, in both the release and insider versions.

I'm cross-debugging a raspberry pi from linux.  What I see is that the program loads as expected and stops with a temporary breakpoint in main.  Clicking 'continue' resumes execution, but clicking 'pause' afterward has no effect.  Clicking 'stop' exits the debug session, leaving the program executing on the target.

Source code and launch.json are attached.

I've also tested with gdb via command line and eclipse CDT.  Both work as expected.

With the release version I see this:

<--   C (continue-12): {"command":"continue","arguments":{"threadId":1},"type":"request","seq":12}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (86160) <--exec-continue\n"},"seq":526}
1: (86160) <--exec-continue
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (86162) ->^running\n"},"seq":528}
1: (86162) ->^running
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (86169) ->*running,thread-id=\"all\"\n"},"seq":531}
1: (86169) ->*running,thread-id="all"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (86173) ->(gdb)\n"},"seq":533}
1: (86173) ->(gdb)
--> R (continue-12): {"type":"response","request_seq":12,"success":true,"command":"continue","body":{},"seq":530}
<--   C (pause-13): {"command":"pause","arguments":{"threadId":1},"type":"request","seq":13}
--> R (pause-13): {"type":"response","request_seq":13,"success":true,"command":"pause","body":{},"seq":537}

With the insider version I see this:

<--   C (continue-13): {"command":"continue","arguments":{"threadId":1},"type":"request","seq":13}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (15910) <--exec-continue\n"},"seq":529}
1: (15910) <--exec-continue
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (15910) ->^running\n"},"seq":531}
1: (15910) ->^running
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (15911) ->*running,thread-id=\"all\"\n"},"seq":534}
1: (15911) ->*running,thread-id="all"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (15911) ->(gdb)\n"},"seq":536}
1: (15911) ->(gdb)
--> R (continue-13): {"type":"response","request_seq":13,"success":true,"command":"continue","body":{},"seq":532}
<--   C (pause-14): {"command":"pause","arguments":{"threadId":1},"type":"request","seq":14}
--> R (pause-14): {"type":"response","request_seq":14,"success":true,"command":"pause","body":{},"seq":540}


Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-67-generic

Version: 1.55.0-insider
Commit: 8437d38d364ba93b53c1e659c20b1c86f710ec28
Date: 2021-03-24T08:12:31.166Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-67-generic

[hello.cpp.txt](https://github.com/microsoft/MIEngine/files/6200508/hello.cpp.txt)
[launch..json.txt](https://github.com/microsoft/MIEngine/files/6200509/launch.json.txt)

**Comment by fbs2016** [comment]
I meet similar issue on latest extension https://github.com/microsoft/vscode-cpptools/issues/7719 Unable to set breakpoint or pause on a running application with extended-remote connection debug.
@haneefdm  Could you share the following operation? Thanks
 _I know the workaround is to Control-C in the shell window. It only requires about 4 lines in the launch.json file,_
