### ISSUE TITLE
vsdbg vs2017u5 broken?

### ISSUE THREAD

**Issue by allevyMS** [microsoft/MIEngine#892]
both of these commands return the same version: 
getvsdbg.sh -v vs2019 -l /vsdbg 
getvsdbg.sh -v vs2017u5 -l /vsdbg 

vsdbg-16-2-10709-2

how do I get the previous version of vsdbg? 
my flow currently relies on the --attach switch which is missing in the latest version

**Comment by gregg-miskelly** [comment]
What are you using to connect to vsdbg that still worked?

**Comment by allevyMS** [comment]
I follow what is outlined in this blog to debug net core from kubernetes: 
https://medium.com/@pavel.agarkov/debugging-asp-net-core-app-running-in-kubernetes-minikube-from-visual-studio-2017-on-windows-6671ddc23d93

It has been working till recently, but now crashes with a "unknown switch --attach" during debugger initialization

**Comment by allevyMS** [comment]
I am assuming a version of vsdbg where this still works exists, I just can't find recent older versions (or a list of versions anywhere) to try

**Comment by gregg-miskelly** [comment]
Thanks. What version of VS 2017 are you you using? My recollection is that MIEngine dropped support for vsdbg in VS 2017 version 15.3.

At any rate, to answer your question, there are two ways you can make this work again -
1. Instead of using `Debug.MIDebugLaunch` to attach to a process, you can do something very similar using `DebugAdapterHost.Launch` see [instructions](https://github.com/microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio#attaching) for more information.
2. You can hardcode the last version of vsdbg that supported that option to the GetVsDbg.ps1/sh script. Example: `& "$env:TEMP\GetVsDbg.ps1" -VersionNumber 16.0.20419.1 -RuntimeID linux-x64 -InstallPath "$env:
USERPROFILE\vsdbg"`

**Comment by allevyMS** [comment]
perfect answer, thanks Gregg!

I will be doing 2 which unblocked me immediately, I will work on 1 when I get a chance

**Comment by ajay-sainy** [comment]
@allevyMS  Could you please let me know which version of vsdbg supported --attach? I am also facing the same issue.

**Comment by allevyMS** [comment]
I believe 16.0.20419.1 is the last one

**Comment by m86194** [comment]
It appears that 16.0.20419.1 is not available anymore on the download servers.

**Comment by pieandcakes** [comment]
@WardenGnaw @gregg-miskelly

**Comment by WardenGnaw** [comment]
@m86194

https://vsdebugger.azureedge.net/vsdbg-16-0-20419-1/vsdbg-linux-x64.zip is still available. 

I also ran:
```
.\GetVsDbg.ps1 -VersionNumber 16.0.20419.1 -RuntimeID linux-x64 -InstallPath ${install_path}
```
And it successfully ran
```
Info: Using vsdbg version '16.0.20419.1'
Info: Using Runtime ID 'linux-x64'
Info: Successfully installed vsdbg
```

Was there an error you were encountering when you ran `GetVsdbg`?
